# Generated by Django 4.1.7 on 2023-04-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_video_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('paye', models.CharField(max_length=50)),
                ('lesson', models.CharField(max_length=50)),
                ('video', models.FileField(upload_to='video/%y')),
                ('slug', models.SlugField()),
                ('status', models.CharField(choices=[('paye7_season1', 'paye7_season1')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
